from enum import Enum
from app.core.const.clima import PRECIPITACAO, PRESSAO, PRESSAO_MAX, PRESSAO_MIN, RADIACAO, TEMP_AR, TEMP_ORVALHO, TEMP_MAX, TEMP_MIN, ORVALHO_MAX, ORVALHO_MIN, UMIDADE_MAX, UMIDADE_MIN, UMIDADE, VENTO_DIRECAO, VENTO_RAJADA, VENTO_VELOCIDADE

class ColunaClima(str, Enum):
    PRECIPITACAO        = PRECIPITACAO
    PRESSAO             = PRESSAO
    PRESSAO_MAX         = PRESSAO_MAX
    PRESSAO_MIN         = PRESSAO_MIN
    RADIACAO            = RADIACAO
    TEMP_AR             = TEMP_AR
    TEMP_ORVALHO        = TEMP_ORVALHO
    TEMP_MAX            = TEMP_MAX
    TEMP_MIN            = TEMP_MIN
    ORVALHO_MAX         = ORVALHO_MAX
    ORVALHO_MIN         = ORVALHO_MIN
    UMIDADE_MAX         = UMIDADE_MAX
    UMIDADE_MIN         = UMIDADE_MIN
    UMIDADE             = UMIDADE
    VENTO_DIRECAO       = VENTO_DIRECAO
    VENTO_RAJADA        = VENTO_RAJADA
    VENTO_VELOCIDADE    = VENTO_VELOCIDADE
